apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: userdefinealert
  namespace: test-application
spec:
  groups:
  - name: userdefine
    rules:
    - alert: SurotePodNotRunning
      expr: sum(kube_pod_status_phase{phase!~'Running|Succeeded'}) > 0
      labels:
        severity: warning
      annotations:
        description: investigate more with "oc get pod -A | grep -v 'Running\|Completed'". Created by USER
