apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-resource-quota
  name: demo-resource-quota
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-resource-quota
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-resource-quota
    spec:
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-call:52f987b597c5e2425cad791d32060cbdf8091150
        name: py-call-quota
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
