apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines:
   - name: infrastructure-audit-logs
     inputRefs:
     - infrastructure
     - audit
     - application
     outputRefs:
     - default
